/* ============================================================
   قاموسُ اللغات — العربيّةُ مفتاحٌ، والإنجليزيّةُ والماليزيّةُ قيمتان

   يُملأ موجةً بعد موجة، ويفرض حارسُ `i18n-scan.cjs` اكتمالَه: ما لم
   يُترجَم ظهر عربيًّا في شاشةٍ إنجليزيّة — وهو عطبٌ لا تكشفه تجربةُ
   العربيّة إطلاقًا.

   والمفاتيحُ **ذرّيّة** قدر المستطاع: المصطلحُ الواحد يُترجَم مرّةً،
   ثم يُركّبه المحرّكُ في الجمل المركّبة باستبدالٍ داخليّ. فلا يُترجَم
   «المهام · ٥ جارية» بل «المهام» و«جارية».
   ============================================================ */

/* ─────────────  الإنجليزية  ───────────── */
DICT.en = {
/* — التنقّل: المجموعات — */
'العمليات':'Operations',
'الموظفون':'Personnel',
'المتابعة':'Follow-up',
'السجلات والنشر':'Records & Publishing',
'إدارة الحركة':'Transport Management',
'العرض':'Display',

/* — التنقّل: الأقسام — */
'لوحة العمليات':'Operations Dashboard',
'الوضع الآن — لوحة تُخصَّص':'Current status — a configurable dashboard',
'المهام':'Tasks',
'أربعة أنواع وأدلّتها':'Four types and their guides',
'أدلة التنفيذ':'Execution Guides',
'الخط الزمني':'Timeline',
'مسار اليوم لكل مجموعة':'Each group’s route for the day',
'البلاغات':'Reports',
'ما يرفعه الميدان والحاجّ — بآليّة تصعيده':'Raised by the field and by pilgrims — with its escalation rule',
'الباصات والمرشدون والعقود':'Buses, guides and contracts',
'النقل':'Transport',
'المرشدون':'Guides',
'عقود النقل':'Transport Contracts',
'السجلّ والتسكين والتعاقد':'Records, assignment and contracting',
'سجلّ الموظفين':'Personnel Register',
'الفرق والمجموعات':'Teams & Groups',
'تبديل الشِفتات':'Shift Swaps',
'الإجراءات':'Disciplinary Actions',
'الإنذارات':'Warnings',
'التشكيل':'Formation',
'مشرفون وليدرز ومحسنون — ثلاث خطوات':'Supervisors, leaders and muhsens — three steps',
'التشكيل السريع':'Quick Formation',
'مجموعة كاملة في صندوق واحد':'A complete group in one box',
'الجهات والفنادق':'Organisations & Hotels',
'تُضاف وتُعدَّل — ويقرؤها النظام':'Added and edited — and read by the system',
'ما يصعد من الميدان':'What escalates from the field',
'طلبات الدعم':'Support Requests',
'الحجاج':'Pilgrims',
'السجلّ الأصل — غرفهم وحالاتهم':'The master register — their rooms and their status',
'الجودة والتقييم':'Quality & Rating',
'تقييم المشرفين والحجاج':'Ratings by supervisors and pilgrims',
'الإشعارات':'Notifications',
'إلى المحسن أو الحاجّ أو الكنترول':'To the muhsen, the pilgrim or Control',
'سجل النظام':'System Log',
'كل قرار بصاحبه ووقته':'Every decision with its author and time',
'كتالوج البلاغات':'Report Catalogue',
'التصنيفات وآليّات التصعيد والمهل':'Categories, escalation rules and deadlines',
'الصلاحيات':'Permissions',
'من يرى ماذا — وأمن مستوى الصفّ':'Who sees what — and row-level security',
'الإعدادات':'Settings',
'إعدادات الموقع والتجربة':'Site and experience settings',
'فريق امتثال':'Imtithal Team',
'الاحتياط':'Reserve',
'التذاكر':'Tickets',
'التذاكر والبلاغات':'Tickets & Reports',

/* — الشريط العلويّ والهوية — */
'مُحسن · الكنترول':'Muhsen · Control',
'غرفة العمليات — موسم حج ١٤٤٨ هـ':'Operations Room — Hajj Season 1448 AH',
'نظام مُحسن · نُزلي':'Muhsen System · Nozoly',
'مهام جارية':'Tasks in progress',
'الحوادث':'Incidents',
'لوحة الأوامر':'Command Palette',
'جدار العرض':'Display Wall',
'الاختصارات':'Shortcuts',
'الوضع الليلي':'Night Mode',
'الوضع النهاري':'Day Mode',
'تبديل الوضع':'Toggle mode',
'هويتك ونطاقك':'Your role and scope',
'الأقسام':'Sections',
'طيّ القائمة':'Collapse menu',
'توسيع':'Expand',
'طيّ':'Collapse',
'القائمة':'Menu',
'إغلاق':'Close',
'توسيع العرض':'Widen',
'تضييق العرض':'Narrow',
'رجوع':'Back',
'الصفحة':'Page',

/* — الأزرار والأفعال الشائعة — */
'حفظ':'Save',
'إلغاء':'Cancel',
'تنفيذ':'Apply',
'تعديل':'Edit',
'حذف':'Delete',
'إضافة':'Add',
'نسخ':'Duplicate',
'اعتماد':'Approve',
'رفض':'Reject',
'إرسال':'Send',
'تصدير إكسل':'Export to Excel',
'طباعة':'Print',
'معاينة':'Preview',
'بحث':'Search',
'الكل':'All',
'دخول':'Sign in',
'خروج':'Sign out',
'التالي':'Next',
'السابق':'Previous',
'المزيد':'More',
'إرفاق ملف':'Attach file',
'تحميل':'Download',
'رفع':'Upload',
'فلاتر أخرى':'More filters',
'امسح الفلاتر':'Clear filters',

/* — الحالات — */
'مفتوح':'Open',
'مفتوحة':'Open',
'مغلق':'Closed',
'مغلقة':'Closed',
'قيد المعالجة':'In progress',
'جارية':'Running',
'منجزة':'Completed',
'متأخّرة':'Late',
'مجدولة':'Scheduled',
'ملغاة':'Cancelled',
'مسودّة':'Draft',
'معتمد':'Approved',
'ساري':'Active',
'منتهٍ':'Expired',
'قائم':'Standing',
'بانتظار القرار':'Awaiting decision',
'بانتظار قرارك':'Awaiting your decision',
'لُبّي':'Fulfilled',
'لُبّيت':'Fulfilled',
'اعتُذر':'Declined',
'مرتفع':'High',
'متوسط':'Medium',
'منخفض':'Low',
'عاجلة':'Urgent',
'حرجة':'Critical',
'عادية':'Normal',
'نشط':'Active',
'حاضر':'Present',
'غير حاضر':'Absent',
'متاح':'Available',

/* — المسمّيات — */
'محسن':'Muhsen',
'المحسن':'The muhsen',
'محسنون':'Muhsens',
'المحسنون':'The muhsens',
'ليدر':'Leader',
'الليدر':'The leader',
'ليدرز':'Leaders',
'مشرف':'Supervisor',
'المشرف':'The supervisor',
'مشرفون':'Supervisors',
'الكنترول':'Control',
'حاجّ':'Pilgrim',
'حاج':'Pilgrim',
'الحاجّ':'The pilgrim',
'الميدان':'The field',
'الجهة':'Organisation',
'الفندق':'Hotel',
'الفنادق':'Hotels',
'المجموعة':'Group',
'مجموعة':'Group',
'الفريق':'Team',
'فريق':'Team',
'بلا فريق':'No team',
'إدارة عليا':'Executive',
'بعثة':'Mission',
'شركة':'Company',
'مشاعر':'Mashaer',
'إعاشة':'Catering',
'مراكز':'Centres',
'مشرفو المدينة':'Madinah Supervisors',
'كل النظام':'Entire system',
'جهته وحدها':'Their organisation only',
'فندقه ومن فيه':'Their hotel and its people',
'اختصاصه عبر الجهات':'Their domain across organisations',
'بياناته وحدها':'Their own data only',

/* — المواقع — */
'مكة المكرمة':'Makkah',
'المدينة المنورة':'Madinah',
'المشاعر':'The Holy Sites',
'جدة':'Jeddah',
'منى':'Mina',
'عرفة':'Arafah',
'مزدلفة':'Muzdalifah',
'الجمرات':'Jamarat',
'المسجد الحرام':'The Grand Mosque',
'مزارات':'Ziyarat Sites',

/* — عناصر عامّة — */
'ملاحظة':'Note',
'ملاحظات':'Notes',
'السبب':'Reason',
'التصنيف':'Category',
'النوع':'Type',
'الأولوية':'Priority',
'الحالة':'Status',
'الوقت':'Time',
'التاريخ':'Date',
'المدة':'Duration',
'العدد':'Count',
'الاسم':'Name',
'الوصف':'Description',
'التفاصيل':'Details',
'العنوان':'Title',
'الملفّ':'File',
'السجلّ':'Log',
'قيدًا':'entries',
'لا قيود':'No entries',
'بلا قيد':'No record',
'المصدر':'Source',
'القناة':'Channel',
'المسؤول':'Owner',
'الإسناد':'Assignment',
'مُسنَدة':'Assigned',
'بلا إسناد':'Unassigned',
'لم تُسنَد بعد':'Not yet assigned',
'لم يُسنَد بعد':'Not yet assigned',
'المُسنَد إليه':'Assigned to',
'الردّ':'Reply',
'المحادثة':'Conversation',
'لا ردّ بعد':'No reply yet',
'من':'From',
'إلى':'To',
'اليوم':'Today',
'أمس':'Yesterday',
'غدًا':'Tomorrow',
'الآن':'Now',
'دقيقة':'minute',
'دقائق':'minutes',
'ساعة':'hour',
'ساعات':'hours',
'يوم':'day',
'أيّام':'days',
'حالًا':'Immediately',
'م.ب':'MB',
'ك.ب':'KB',
'نظيف':'Clean',
'بند':'item',
'لا شيء معلّق':'Nothing pending',
'يحتاج قرارك الآن':'Needs your decision now',
'لا بيانات':'No data',
'بلا ملاحظات':'No findings'
};

/* ─────────────  الماليزية  ───────────── */
DICT.ms = {
/* — Navigasi: kumpulan — */
'العمليات':'Operasi',
'الموظفون':'Kakitangan',
'المتابعة':'Susulan',
'السجلات والنشر':'Rekod & Penerbitan',
'إدارة الحركة':'Pengurusan Pergerakan',
'العرض':'Paparan',

/* — Navigasi: bahagian — */
'لوحة العمليات':'Papan Pemuka Operasi',
'الوضع الآن — لوحة تُخصَّص':'Keadaan semasa — papan pemuka boleh disesuaikan',
'المهام':'Tugasan',
'أربعة أنواع وأدلّتها':'Empat jenis dan panduannya',
'أدلة التنفيذ':'Panduan Pelaksanaan',
'الخط الزمني':'Garis Masa',
'مسار اليوم لكل مجموعة':'Laluan harian bagi setiap kumpulan',
'البلاغات':'Laporan',
'ما يرفعه الميدان والحاجّ — بآليّة تصعيده':'Dikemukakan oleh petugas dan jemaah — dengan kaedah eskalasinya',
'الباصات والمرشدون والعقود':'Bas, pembimbing dan kontrak',
'النقل':'Pengangkutan',
'المرشدون':'Pembimbing',
'عقود النقل':'Kontrak Pengangkutan',
'السجلّ والتسكين والتعاقد':'Rekod, penempatan dan kontrak',
'سجلّ الموظفين':'Daftar Kakitangan',
'الفرق والمجموعات':'Pasukan & Kumpulan',
'تبديل الشِفتات':'Pertukaran Syif',
'الإجراءات':'Tindakan Tatatertib',
'الإنذارات':'Amaran',
'التشكيل':'Pembentukan',
'مشرفون وليدرز ومحسنون — ثلاث خطوات':'Penyelia, ketua dan muhsin — tiga langkah',
'التشكيل السريع':'Pembentukan Pantas',
'مجموعة كاملة في صندوق واحد':'Satu kumpulan lengkap dalam satu kotak',
'الجهات والفنادق':'Organisasi & Hotel',
'تُضاف وتُعدَّل — ويقرؤها النظام':'Ditambah dan disunting — dan dibaca oleh sistem',
'ما يصعد من الميدان':'Perkara yang dieskalasi dari lapangan',
'طلبات الدعم':'Permohonan Sokongan',
'الحجاج':'Jemaah',
'السجلّ الأصل — غرفهم وحالاتهم':'Daftar induk — bilik dan status mereka',
'الجودة والتقييم':'Kualiti & Penilaian',
'تقييم المشرفين والحجاج':'Penilaian oleh penyelia dan jemaah',
'الإشعارات':'Pemberitahuan',
'إلى المحسن أو الحاجّ أو الكنترول':'Kepada muhsin, jemaah atau Kawalan',
'سجل النظام':'Log Sistem',
'كل قرار بصاحبه ووقته':'Setiap keputusan dengan pemilik dan masanya',
'كتالوج البلاغات':'Katalog Laporan',
'التصنيفات وآليّات التصعيد والمهل':'Kategori, kaedah eskalasi dan tempoh',
'الصلاحيات':'Kebenaran',
'من يرى ماذا — وأمن مستوى الصفّ':'Siapa melihat apa — dan keselamatan peringkat baris',
'الإعدادات':'Tetapan',
'إعدادات الموقع والتجربة':'Tetapan laman dan pengalaman',
'فريق امتثال':'Pasukan Imtithal',
'الاحتياط':'Simpanan',
'التذاكر':'Tiket',
'التذاكر والبلاغات':'Tiket & Laporan',

/* — Bar atas dan identiti — */
'مُحسن · الكنترول':'Muhsin · Kawalan',
'غرفة العمليات — موسم حج ١٤٤٨ هـ':'Bilik Operasi — Musim Haji 1448H',
'نظام مُحسن · نُزلي':'Sistem Muhsin · Nozoly',
'مهام جارية':'Tugasan berjalan',
'الحوادث':'Insiden',
'لوحة الأوامر':'Palet Arahan',
'جدار العرض':'Dinding Paparan',
'الاختصارات':'Pintasan',
'الوضع الليلي':'Mod Malam',
'الوضع النهاري':'Mod Siang',
'تبديل الوضع':'Tukar mod',
'هويتك ونطاقك':'Peranan dan skop anda',
'الأقسام':'Bahagian',
'طيّ القائمة':'Kuncupkan menu',
'توسيع':'Kembangkan',
'طيّ':'Kuncupkan',
'القائمة':'Menu',
'إغلاق':'Tutup',
'توسيع العرض':'Lebarkan',
'تضييق العرض':'Sempitkan',
'رجوع':'Kembali',
'الصفحة':'Halaman',

/* — Tindakan lazim — */
'حفظ':'Simpan',
'إلغاء':'Batal',
'تنفيذ':'Laksana',
'تعديل':'Sunting',
'حذف':'Padam',
'إضافة':'Tambah',
'نسخ':'Salin',
'اعتماد':'Luluskan',
'رفض':'Tolak',
'إرسال':'Hantar',
'تصدير إكسل':'Eksport ke Excel',
'طباعة':'Cetak',
'معاينة':'Pratonton',
'بحث':'Cari',
'الكل':'Semua',
'دخول':'Log masuk',
'خروج':'Log keluar',
'التالي':'Seterusnya',
'السابق':'Sebelumnya',
'المزيد':'Lagi',
'إرفاق ملف':'Lampirkan fail',
'تحميل':'Muat turun',
'رفع':'Muat naik',
'فلاتر أخرى':'Penapis lain',
'امسح الفلاتر':'Kosongkan penapis',

/* — Status — */
'مفتوح':'Terbuka',
'مفتوحة':'Terbuka',
'مغلق':'Ditutup',
'مغلقة':'Ditutup',
'قيد المعالجة':'Sedang diuruskan',
'جارية':'Berjalan',
'منجزة':'Selesai',
'متأخّرة':'Lewat',
'مجدولة':'Dijadualkan',
'ملغاة':'Dibatalkan',
'مسودّة':'Draf',
'معتمد':'Diluluskan',
'ساري':'Aktif',
'منتهٍ':'Tamat tempoh',
'قائم':'Masih berkuat kuasa',
'بانتظار القرار':'Menunggu keputusan',
'بانتظار قرارك':'Menunggu keputusan anda',
'لُبّي':'Dipenuhi',
'لُبّيت':'Dipenuhi',
'اعتُذر':'Ditolak',
'مرتفع':'Tinggi',
'متوسط':'Sederhana',
'منخفض':'Rendah',
'عاجلة':'Segera',
'حرجة':'Kritikal',
'عادية':'Biasa',
'نشط':'Aktif',
'حاضر':'Hadir',
'غير حاضر':'Tidak hadir',
'متاح':'Tersedia',

/* — Peranan — */
'محسن':'Muhsin',
'المحسن':'Muhsin tersebut',
'محسنون':'Muhsin',
'المحسنون':'Para muhsin',
'ليدر':'Ketua',
'الليدر':'Ketua tersebut',
'ليدرز':'Ketua',
'مشرف':'Penyelia',
'المشرف':'Penyelia tersebut',
'مشرفون':'Penyelia',
'الكنترول':'Kawalan',
'حاجّ':'Jemaah',
'حاج':'Jemaah',
'الحاجّ':'Jemaah tersebut',
'الميدان':'Lapangan',
'الجهة':'Organisasi',
'الفندق':'Hotel',
'الفنادق':'Hotel',
'المجموعة':'Kumpulan',
'مجموعة':'Kumpulan',
'الفريق':'Pasukan',
'فريق':'Pasukan',
'بلا فريق':'Tiada pasukan',
'إدارة عليا':'Eksekutif',
'بعثة':'Misi',
'شركة':'Syarikat',
'مشاعر':'Masyair',
'إعاشة':'Katering',
'مراكز':'Pusat',
'مشرفو المدينة':'Penyelia Madinah',
'كل النظام':'Seluruh sistem',
'جهته وحدها':'Organisasinya sahaja',
'فندقه ومن فيه':'Hotelnya dan penghuninya',
'اختصاصه عبر الجهات':'Bidangnya merentas organisasi',
'بياناته وحدها':'Datanya sahaja',

/* — Lokasi — */
'مكة المكرمة':'Makkah',
'المدينة المنورة':'Madinah',
'المشاعر':'Masyair',
'جدة':'Jeddah',
'منى':'Mina',
'عرفة':'Arafah',
'مزدلفة':'Muzdalifah',
'الجمرات':'Jamarat',
'المسجد الحرام':'Masjidil Haram',
'مزارات':'Tapak Ziarah',

/* — Umum — */
'ملاحظة':'Catatan',
'ملاحظات':'Catatan',
'السبب':'Sebab',
'التصنيف':'Kategori',
'النوع':'Jenis',
'الأولوية':'Keutamaan',
'الحالة':'Status',
'الوقت':'Masa',
'التاريخ':'Tarikh',
'المدة':'Tempoh',
'العدد':'Bilangan',
'الاسم':'Nama',
'الوصف':'Penerangan',
'التفاصيل':'Butiran',
'العنوان':'Tajuk',
'الملفّ':'Fail',
'السجلّ':'Log',
'قيدًا':'catatan',
'لا قيود':'Tiada catatan',
'بلا قيد':'Tiada rekod',
'المصدر':'Sumber',
'القناة':'Saluran',
'المسؤول':'Pemilik',
'الإسناد':'Penugasan',
'مُسنَدة':'Ditugaskan',
'بلا إسناد':'Belum ditugaskan',
'لم تُسنَد بعد':'Belum ditugaskan',
'لم يُسنَد بعد':'Belum ditugaskan',
'المُسنَد إليه':'Ditugaskan kepada',
'الردّ':'Balasan',
'المحادثة':'Perbualan',
'لا ردّ بعد':'Belum ada balasan',
'من':'Daripada',
'إلى':'Kepada',
'اليوم':'Hari ini',
'أمس':'Semalam',
'غدًا':'Esok',
'الآن':'Sekarang',
'دقيقة':'minit',
'دقائق':'minit',
'ساعة':'jam',
'ساعات':'jam',
'يوم':'hari',
'أيّام':'hari',
'حالًا':'Serta-merta',
'م.ب':'MB',
'ك.ب':'KB',
'نظيف':'Bersih',
'بند':'perkara',
'لا شيء معلّق':'Tiada yang tertangguh',
'يحتاج قرارك الآن':'Memerlukan keputusan anda sekarang',
'لا بيانات':'Tiada data',
'بلا ملاحظات':'Tiada penemuan'
};
